name: "main"

on:
  pull_request:
  push:
    branches-ignore:
      - main

env:
  extensions: "xml mbstring curl openssl dom xdebug"
  composer-install-args: "--no-progress --no-interaction --prefer-dist --no-scripts"

jobs:
  qa:
    name: "Quality assurance"
    runs-on: "${{ matrix.operating-system }}"

    strategy:
      matrix:
        include:
          - operating-system: "ubuntu-latest"
            php-version: "8.0"
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: none

      - uses: php-actions/composer@v6
        with:
          php_version: "${{ matrix.php-version }}"
          args:  "${{ env.composer-install-args }}"
      - run: vendor/bin/ecs check src tests