name: "main"

on:
  pull_request:
  push:
    branches-ignore:
      - main

env:
  extensions: "xml mbstring curl openssl dom xdebug"
  composer-install-args: "--no-progress --no-interaction --prefer-dist --no-scripts"

jobs:
  tests:
    name: "Tests"
    runs-on: "${{ matrix.operating-system }}"

    strategy:
      matrix:
        include:
          - operating-system: "ubuntu-latest"
            php-version: "8.0"
          - operating-system: "ubuntu-latest"
            php-version: "7.4"
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: none

      - uses: php-actions/composer@v6
        with:
          php_version: "${{ matrix.php-version }}"
          args: "${{ env.composer-install-args }}"

      - name: PHPUnit
        uses: php-actions/phpunit@v3
        env:
          FO_ID_DS: '${{ secrets.FO_ID_DS }}'
          FO_LOGIN_USER: '${{ secrets.FO_LOGIN_USER }}'
          FO_PASSWORD_USER: '${{ secrets.FO_PASSWORD_USER }}'
          OVM_ID_DS: '${{ secrets.OVM_ID_DS }}'
          OVM_LOGIN_USER: '${{ secrets.OVM_LOGIN_USER }}'
          OVM_PASSWORD_USER: '${{ secrets.OVM_PASSWORD_USER }}'
          IS_PRODUCTION: '${{ secrets.IS_PRODUCTION }}'
        with:
          bootstrap: vendor/autoload.php
          configuration: tests/phpunit.xml
          php_version: "${{ matrix.php-version }}"
          php_extensions: "${{ env.extensions }}"
